---
title: "A Brief Introduction to Research Design"
author: "Wiliam Murrah"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This post is based on the second chapter of the open source textbook *Learning Statistics with R: A tutorial for psychology students and other beginners*, by Danielle Navarro.
The book can be found at https://learningstatisticswithr.com/.

## Psychological Measurement

Scales of measurement can be a bit tricky at first. After reading chapter 2 of *lsr*, read the following scenarios and see if you can answer the questions below.
These questions are taken from another open source textbook *OpenIntro Statistics*, which can be found at https://www.openintro.org/.


### EXAMPLE 1.5

Data were collected about students in a statistics course. Three variables were recorded for each student: number of siblings, student height, and whether the student had previously taken a statistics course. 

**Question:** Classify each of the variables as continuous numerical, discrete numerical, or nominal(categorical).

**Answer:** The number of siblings and student height represent numerical variables. Because the number of siblings is a count, it is discrete. Height varies continuously, so it is a continuous numerical variable.
The last variable classifies students into two categories – those who have and those who have not taken a statistics course – which makes this variable nominal.

### GUIDED PRACTICE 1.6
An experiment is evaluating the effectiveness of a new drug in treating migraines. A group variable is used to indicate the experiment group for each patient: treatment or control. The `num_migraines` variable represents the number of migraines the patient experienced during a 3-month period.
Classify each variable as either numerical or nominal?^[There group variable can take just one of two group names, making it categorical. The `num_migraines` variable
describes a count of the number of migraines, which is an outcome where basic arithmetic is sensible, which means this
is numerical outcome; more specifically, since it represents a count, `num_migraines` is a discrete numerical variable.]

## Internal Validity versus External Validity

